from typing import List, Optional, Protocol, Tuple
from app.domain.models import (
    AnalysisItem,
    AnalysisRun,
    Application,
    Job,
    JobSkill,
    Recommendation,
    RefreshToken,
    SkillCatalog,
    StudentProfile,
    StudentSkill,
    User,
)


class UserRepositoryProtocol(Protocol):
    def create(self, user: User) -> User: ...
    def get_by_id(self, user_id: int) -> Optional[User]: ...
    def get_by_email(self, email: str) -> Optional[User]: ...
    def list_all(self, skip: int = 0, limit: int = 50) -> Tuple[List[User], int]: ...
    def save_refresh_token(self, token: RefreshToken) -> RefreshToken: ...
    def get_refresh_token(self, token_hash: str) -> Optional[RefreshToken]: ...
    def revoke_refresh_token(self, token_hash: str) -> bool: ...
    def revoke_family_tokens(self, family_id: str) -> int: ...


class StudentRepositoryProtocol(Protocol):
    def create_student(self, student: StudentProfile) -> StudentProfile: ...
    def get_student_by_id(self, student_id: int) -> Optional[StudentProfile]: ...
    def get_student_by_user_id(self, user_id: int) -> Optional[StudentProfile]: ...
    def get_student_by_email(self, email: str) -> Optional[StudentProfile]: ...
    def update_student(self, student: StudentProfile) -> StudentProfile: ...
    def list_students(self, skip: int = 0, limit: int = 50) -> Tuple[List[StudentProfile], int]: ...
    def upsert_skill(self, student_id: int, skill_id: int, proficiency: int) -> StudentSkill: ...
    def delete_skill(self, student_id: int, skill_id: int) -> bool: ...
    def get_skills(self, student_id: int) -> List[StudentSkill]: ...

    # Backwards compatibility methods
    def create_profile(self, profile: StudentProfile) -> StudentProfile: ...
    def get_profile_by_user_id(self, user_id: int) -> Optional[StudentProfile]: ...
    def get_profile_by_id(self, profile_id: int) -> Optional[StudentProfile]: ...
    def update_profile(self, profile: StudentProfile) -> StudentProfile: ...
    def list_profiles(self, skip: int = 0, limit: int = 50) -> Tuple[List[StudentProfile], int]: ...


class SkillRepositoryProtocol(Protocol):
    def create(self, skill: SkillCatalog) -> SkillCatalog: ...
    def get_by_id(self, skill_id: int) -> Optional[SkillCatalog]: ...
    def get_by_normalized_name(self, normalized_name: str) -> Optional[SkillCatalog]: ...
    def update(self, skill: SkillCatalog) -> SkillCatalog: ...
    def delete(self, skill_id: int) -> bool: ...
    def list_all(
        self,
        category: Optional[str] = None,
        search: Optional[str] = None,
        skip: int = 0,
        limit: int = 50,
    ) -> Tuple[List[SkillCatalog], int]: ...


class JobRepositoryProtocol(Protocol):
    def create_job(self, job: Job) -> Job: ...
    def get_job_by_id(self, job_id: int) -> Optional[Job]: ...
    def update_job(self, job: Job) -> Job: ...
    def delete_job(self, job_id: int) -> bool: ...
    def list_jobs(
        self,
        employer_id: Optional[int] = None,
        is_active: Optional[bool] = None,
        search: Optional[str] = None,
        skip: int = 0,
        limit: int = 50,
    ) -> Tuple[List[Job], int]: ...
    def upsert_skill(self, job_id: int, skill_id: int, required_level: int, mandatory: bool) -> JobSkill: ...
    def delete_skill(self, job_id: int, skill_id: int) -> bool: ...
    def get_skills(self, job_id: int) -> List[JobSkill]: ...


class MatchingRepositoryProtocol(Protocol):
    def save_analysis(
        self, run: AnalysisRun, items: List[AnalysisItem], recs: List[Recommendation]
    ) -> AnalysisRun: ...
    def get_analysis_run(self, run_id: str) -> Optional[AnalysisRun]: ...
    def get_latest_run(self, student_id: int, job_id: int) -> Optional[AnalysisRun]: ...
    def list_runs_for_student(
        self, student_id: int, skip: int = 0, limit: int = 50
    ) -> Tuple[List[AnalysisRun], int]: ...
    def list_recommendations(self, student_id: int, job_id: int) -> List[Recommendation]: ...
    def list_candidate_runs_for_job(
        self, job_id: int, skip: int = 0, limit: int = 50
    ) -> Tuple[List[AnalysisRun], int]: ...


class ApplicationRepositoryProtocol(Protocol):
    def create_application(self, app: Application) -> Application: ...
    def get_application_by_id(self, app_id: int) -> Optional[Application]: ...
    def get_active_application(self, student_id: int, job_id: int) -> Optional[Application]: ...
    def update_application(self, app: Application) -> Application: ...
    def list_applications(
        self,
        student_id: Optional[int] = None,
        job_id: Optional[int] = None,
        status: Optional[str] = None,
        skip: int = 0,
        limit: int = 50,
    ) -> Tuple[List[Application], int]: ...
